//! Google Antigravity adapter
//!
//! Generates output for Google Antigravity:
//! - `.agent/rules/<id>.md` - Rules
//! - `.agent/workflows/<id>.md` - Workflows

use std::path::PathBuf;

use crate::adapters::{Diagnostic, DiagnosticSeverity, OutputFile, TargetAdapter};
use crate::error::CalvinResult;
use crate::models::{PromptAsset, Scope, Target};

/// Antigravity adapter
pub struct AntigravityAdapter;

impl AntigravityAdapter {
    pub fn new() -> Self {
        Self
    }

    /// Generate workflow frontmatter
    fn generate_workflow_frontmatter(&self, asset: &PromptAsset) -> String {
        let mut fm = String::from("---\n");
        fm.push_str(&format!("description: {}\n", asset.frontmatter.description));
        fm.push_str("---\n");
        fm
    }
}

impl Default for AntigravityAdapter {
    fn default() -> Self {
        Self::new()
    }
}

impl TargetAdapter for AntigravityAdapter {
    fn target(&self) -> Target {
        Target::Antigravity
    }

    fn compile(&self, asset: &PromptAsset) -> CalvinResult<Vec<OutputFile>> {
        let mut outputs = Vec::new();
        let footer = self.footer(&asset.source_path.display().to_string());

        // Determine base path based on scope
        // All Antigravity assets go to workflows directory
        let base_path = match asset.frontmatter.scope {
            Scope::User => PathBuf::from("~/.gemini/antigravity/global_workflows"),
            Scope::Project => PathBuf::from(".agent/workflows"),
        };

        // All Antigravity assets use the same YAML frontmatter format
        let path = base_path.join(format!("{}.md", asset.id));
        let frontmatter = self.generate_workflow_frontmatter(asset);

        let content = format!(
            "{}\n{}\n\n{}",
            frontmatter,
            asset.content.trim(),
            footer
        );

        outputs.push(OutputFile::new(path, content));

        Ok(outputs)
    }

    fn validate(&self, output: &OutputFile) -> Vec<Diagnostic> {
        let mut diagnostics = Vec::new();
        
        if output.content.trim().is_empty() {
            diagnostics.push(Diagnostic {
                severity: DiagnosticSeverity::Warning,
                message: "Generated output is empty".to_string(),
                file: Some(output.path.clone()),
            });
        }
        
        diagnostics
    }

    fn security_baseline(&self, _config: &crate::config::Config) -> Vec<OutputFile> {
        // Antigravity security is configured via:
        // - Terminal mode (Auto vs Turbo)
        // - allowlist/denylist files
        // - Browser allowlist
        // These are user-level configs, not project-level
        Vec::new()
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::models::{AssetKind, Frontmatter};

    #[test]
    fn test_antigravity_adapter_compile_policy() {
        let adapter = AntigravityAdapter::new();
        let fm = Frontmatter::new("Code style rules");
        let asset = PromptAsset::new(
            "code-style",
            "policies/code-style.md",
            fm,
            "# Code Style\n\nFollow these rules.",
        );

        let outputs = adapter.compile(&asset).unwrap();
        
        assert_eq!(outputs.len(), 1);
        assert_eq!(
            outputs[0].path,
            PathBuf::from(".agent/workflows/code-style.md")
        );
        // Frontmatter should be at the very beginning with description
        assert!(outputs[0].content.starts_with("---\n"));
        assert!(outputs[0].content.contains("description: Code style rules"));
        // Footer should be at the end
        assert!(outputs[0].content.ends_with("DO NOT EDIT. -->"));
        assert!(outputs[0].content.contains("Generated by Calvin"));
    }

    #[test]
    fn test_antigravity_adapter_compile_action() {
        let adapter = AntigravityAdapter::new();
        let mut fm = Frontmatter::new("Code review workflow");
        fm.kind = AssetKind::Action;
        let asset = PromptAsset::new(
            "code-review",
            "actions/code-review.md",
            fm,
            "# Review Process\n\n1. Check code",
        );

        let outputs = adapter.compile(&asset).unwrap();
        
        assert_eq!(outputs.len(), 1);
        assert_eq!(
            outputs[0].path,
            PathBuf::from(".agent/workflows/code-review.md")
        );
        // Frontmatter should be at the very beginning
        assert!(outputs[0].content.starts_with("---\n"));
        assert!(outputs[0].content.contains("description: Code review workflow"));
        assert!(outputs[0].content.contains("# Review Process"));
        // Footer should be at the end
        assert!(outputs[0].content.ends_with("DO NOT EDIT. -->"));
    }

    #[test]
    fn test_antigravity_adapter_compile_agent() {
        let adapter = AntigravityAdapter::new();
        let mut fm = Frontmatter::new("Senior reviewer");
        fm.kind = AssetKind::Agent;
        let asset = PromptAsset::new(
            "senior-reviewer",
            "agents/senior-reviewer.md",
            fm,
            "You are a senior code reviewer.",
        );

        let outputs = adapter.compile(&asset).unwrap();
        
        assert_eq!(
            outputs[0].path,
            PathBuf::from(".agent/workflows/senior-reviewer.md")
        );
        // Frontmatter should be at the very beginning with description
        assert!(outputs[0].content.starts_with("---\n"));
        assert!(outputs[0].content.contains("description: Senior reviewer"));
        // Footer should be at the end
        assert!(outputs[0].content.ends_with("DO NOT EDIT. -->"));
    }

    #[test]
    fn test_antigravity_workflow_frontmatter() {
        let adapter = AntigravityAdapter::new();
        let mut fm = Frontmatter::new("Test workflow");
        fm.kind = AssetKind::Action;
        let asset = PromptAsset::new("test", "actions/test.md", fm, "");

        let frontmatter = adapter.generate_workflow_frontmatter(&asset);
        
        assert!(frontmatter.starts_with("---\n"));
        assert!(frontmatter.ends_with("---\n"));
        assert!(frontmatter.contains("description: Test workflow"));
    }

    #[test]
    fn test_antigravity_security_baseline_empty() {
        let adapter = AntigravityAdapter::new();
        let config = crate::config::Config::default();
        let baseline = adapter.security_baseline(&config);
        assert!(baseline.is_empty());
    }
}
