//! Google Antigravity adapter
//!
//! Generates output for Google Antigravity:
//! - `.agent/rules/<id>.md` - Rules
//! - `.agent/workflows/<id>.md` - Workflows

use std::path::PathBuf;

use crate::adapters::{Diagnostic, OutputFile, TargetAdapter};
use crate::error::CalvinResult;
use crate::models::{AssetKind, PromptAsset, Target};

/// Antigravity adapter
pub struct AntigravityAdapter;

impl AntigravityAdapter {
    pub fn new() -> Self {
        Self
    }

    /// Generate workflow frontmatter
    fn generate_workflow_frontmatter(&self, asset: &PromptAsset) -> String {
        let mut fm = String::from("---\n");
        fm.push_str(&format!("description: {}\n", asset.frontmatter.description));
        fm.push_str("---\n");
        fm
    }
}

impl Default for AntigravityAdapter {
    fn default() -> Self {
        Self::new()
    }
}

impl TargetAdapter for AntigravityAdapter {
    fn target(&self) -> Target {
        Target::Antigravity
    }

    fn compile(&self, asset: &PromptAsset) -> CalvinResult<Vec<OutputFile>> {
        let mut outputs = Vec::new();
        let header = self.header(&asset.source_path.display().to_string());

        match asset.frontmatter.kind {
            AssetKind::Policy => {
                // Rules go to .agent/rules/
                let path = PathBuf::from(".agent/rules")
                    .join(format!("{}.md", asset.id));

                let content = format!(
                    "{}\n# {}\n\n{}",
                    header,
                    asset.frontmatter.description,
                    asset.content.trim()
                );

                outputs.push(OutputFile::new(path, content));
            }
            AssetKind::Action => {
                // Actions become workflows in .agent/workflows/
                let path = PathBuf::from(".agent/workflows")
                    .join(format!("{}.md", asset.id));

                let frontmatter = self.generate_workflow_frontmatter(asset);
                let content = format!(
                    "{}{}\n{}",
                    header,
                    frontmatter,
                    asset.content.trim()
                );

                outputs.push(OutputFile::new(path, content));
            }
            AssetKind::Agent => {
                // Agents also go to rules with special handling
                let path = PathBuf::from(".agent/rules")
                    .join(format!("{}.md", asset.id));

                let content = format!(
                    "{}\n# Agent: {}\n\n{}",
                    header,
                    asset.frontmatter.description,
                    asset.content.trim()
                );

                outputs.push(OutputFile::new(path, content));
            }
        }

        Ok(outputs)
    }

    fn validate(&self, _output: &OutputFile) -> Vec<Diagnostic> {
        // TODO: Validate against Antigravity best practices
        // - Check for Turbo mode indicators
        // - Validate allowlist references
        Vec::new()
    }

    fn security_baseline(&self) -> Vec<OutputFile> {
        // Antigravity security is configured via:
        // - Terminal mode (Auto vs Turbo)
        // - allowlist/denylist files
        // - Browser allowlist
        // These are user-level configs, not project-level
        Vec::new()
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::models::Frontmatter;

    #[test]
    fn test_antigravity_adapter_compile_policy() {
        let adapter = AntigravityAdapter::new();
        let fm = Frontmatter::new("Code style rules");
        let asset = PromptAsset::new(
            "code-style",
            "policies/code-style.md",
            fm,
            "# Code Style\n\nFollow these rules.",
        );

        let outputs = adapter.compile(&asset).unwrap();
        
        assert_eq!(outputs.len(), 1);
        assert_eq!(
            outputs[0].path,
            PathBuf::from(".agent/rules/code-style.md")
        );
        assert!(outputs[0].content.contains("Generated by Calvin"));
        assert!(outputs[0].content.contains("# Code style rules"));
    }

    #[test]
    fn test_antigravity_adapter_compile_action() {
        let adapter = AntigravityAdapter::new();
        let mut fm = Frontmatter::new("Code review workflow");
        fm.kind = AssetKind::Action;
        let asset = PromptAsset::new(
            "code-review",
            "actions/code-review.md",
            fm,
            "# Review Process\n\n1. Check code",
        );

        let outputs = adapter.compile(&asset).unwrap();
        
        assert_eq!(outputs.len(), 1);
        assert_eq!(
            outputs[0].path,
            PathBuf::from(".agent/workflows/code-review.md")
        );
        assert!(outputs[0].content.contains("description: Code review workflow"));
        assert!(outputs[0].content.contains("# Review Process"));
    }

    #[test]
    fn test_antigravity_adapter_compile_agent() {
        let adapter = AntigravityAdapter::new();
        let mut fm = Frontmatter::new("Senior reviewer");
        fm.kind = AssetKind::Agent;
        let asset = PromptAsset::new(
            "senior-reviewer",
            "agents/senior-reviewer.md",
            fm,
            "You are a senior code reviewer.",
        );

        let outputs = adapter.compile(&asset).unwrap();
        
        assert_eq!(
            outputs[0].path,
            PathBuf::from(".agent/rules/senior-reviewer.md")
        );
        assert!(outputs[0].content.contains("# Agent: Senior reviewer"));
    }

    #[test]
    fn test_antigravity_workflow_frontmatter() {
        let adapter = AntigravityAdapter::new();
        let mut fm = Frontmatter::new("Test workflow");
        fm.kind = AssetKind::Action;
        let asset = PromptAsset::new("test", "actions/test.md", fm, "");

        let frontmatter = adapter.generate_workflow_frontmatter(&asset);
        
        assert!(frontmatter.starts_with("---\n"));
        assert!(frontmatter.ends_with("---\n"));
        assert!(frontmatter.contains("description: Test workflow"));
    }

    #[test]
    fn test_antigravity_security_baseline_empty() {
        let adapter = AntigravityAdapter::new();
        let baseline = adapter.security_baseline();
        assert!(baseline.is_empty());
    }
}
